// Generated by gencpp from file rdt_mqtt/PackedMessage.msg
// DO NOT EDIT!


#ifndef RDT_MQTT_MESSAGE_PACKEDMESSAGE_H
#define RDT_MQTT_MESSAGE_PACKEDMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rdt_mqtt
{
template <class ContainerAllocator>
struct PackedMessage_
{
  typedef PackedMessage_<ContainerAllocator> Type;

  PackedMessage_()
    : channel_name()
    , field()
    , value(0)  {
    }
  PackedMessage_(const ContainerAllocator& _alloc)
    : channel_name(_alloc)
    , field(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _channel_name_type;
  _channel_name_type channel_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _field_type;
  _field_type field;

   typedef int64_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::rdt_mqtt::PackedMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rdt_mqtt::PackedMessage_<ContainerAllocator> const> ConstPtr;

}; // struct PackedMessage_

typedef ::rdt_mqtt::PackedMessage_<std::allocator<void> > PackedMessage;

typedef boost::shared_ptr< ::rdt_mqtt::PackedMessage > PackedMessagePtr;
typedef boost::shared_ptr< ::rdt_mqtt::PackedMessage const> PackedMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rdt_mqtt::PackedMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rdt_mqtt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rdt_mqtt': ['/home/marcus/RMC19/src/rdt_mqtt/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rdt_mqtt::PackedMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rdt_mqtt::PackedMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rdt_mqtt::PackedMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "414500ef2055d204b53a9b00ad95abae";
  }

  static const char* value(const ::rdt_mqtt::PackedMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x414500ef2055d204ULL;
  static const uint64_t static_value2 = 0xb53a9b00ad95abaeULL;
};

template<class ContainerAllocator>
struct DataType< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rdt_mqtt/PackedMessage";
  }

  static const char* value(const ::rdt_mqtt::PackedMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string channel_name\n\
string field\n\
int64 value\n\
";
  }

  static const char* value(const ::rdt_mqtt::PackedMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel_name);
      stream.next(m.field);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PackedMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rdt_mqtt::PackedMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rdt_mqtt::PackedMessage_<ContainerAllocator>& v)
  {
    s << indent << "channel_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.channel_name);
    s << indent << "field: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.field);
    s << indent << "value: ";
    Printer<int64_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RDT_MQTT_MESSAGE_PACKEDMESSAGE_H
